name: Test Code

on:
  pull_request:
    paths:
      - 'internal/**'
      - 'cmd/**'
      - 'go.mod'
      - 'go.sum'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'

      - name: Build
        run: go build -o cultpedia ./cmd

      - name: Run tests
        run: go test ./...

      - name: Run vet
        run: go vet ./...
